version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:movie_app
    container_name: app_container
    command: >
      sh -c "python manage.py wait_for_database && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./app/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=milosz
      - POSTGRES_PASSWORD=milosz
    container_name: postgres_db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis_container

  celery-worker:
    build: .
    command: celery -A movie_app worker -l info
    container_name: celery-worker_container
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app

  celery-beat:
    build: .
    command: celery -A movie_app beat -l info
    container_name: celery-beat_container
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery-worker
