# Generated by Django 4.2.3 on 2023-08-19 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('custom_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('poster_path', models.CharField(default=None, max_length=200)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('on_watchlist', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('watched', 'Watched')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('custom_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
                ('profile_path', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
