# Generated by Django 4.2.3 on 2023-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('custom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('on_watchlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('actor', 'Aktor'), ('director', 'Reżyser'), ('cameraman', 'Kamerzysta'), ('lighting', 'Oświetlenie'), ('sound', 'Dźwięk')], max_length=10)),
                ('movies', models.ManyToManyField(related_name='people', to='base.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list_type', models.CharField(choices=[('movies', 'Filmy'), ('directors', 'Reżyserzy'), ('actors', 'Aktorzy'), ('crew', 'Ekipa')], max_length=10)),
                ('movies', models.ManyToManyField(blank=True, related_name='movie_lists', to='base.movie')),
                ('people', models.ManyToManyField(blank=True, related_name='person_lists', to='base.person')),
            ],
        ),
    ]
