# Generated by Django 4.2.3 on 2023-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='on_watchlist',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('watched', 'Watched')], max_length=10),
        ),
    ]
