# Generated by Django 4.2.3 on 2023-08-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_movie_on_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='list_type',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='people',
        ),
        migrations.AddField(
            model_name='movielist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(to='base.movie'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('persons', models.ManyToManyField(to='base.person')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
