# Generated by Django 4.2.3 on 2023-08-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_personlist_persons_remove_personlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
