# Generated by Django 4.2.3 on 2023-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='movies',
        ),
        migrations.AddField(
            model_name='person',
            name='custom_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='custom_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
