# Generated by Django 4.2.3 on 2023-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_person_id_remove_person_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('actor', 'Aktor'), ('director', 'Reżyser'), ('writer', 'Scenarzysta'), ('cameraman', 'Kamerzysta'), ('lighting', 'Oświetlenie'), ('sound', 'Dźwięk')], max_length=10),
        ),
    ]
