# Generated by Django 4.2.3 on 2023-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_path',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
