# Generated by Django 4.2.3 on 2023-08-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
