# Generated by Django 4.2.3 on 2023-08-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmwebTop250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMDBTop250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OscarWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('release_year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
                ('studio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OscarNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('studio', models.CharField(max_length=255)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='list_management.oscarwinner')),
            ],
        ),
    ]
