# Generated by Django 4.2.3 on 2023-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
