# Generated by Django 4.2.3 on 2023-08-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0002_movielist_description_alter_movielist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='description',
        ),
    ]
