# Generated by Django 4.2.3 on 2023-08-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0002_filmwebtop250_imdbtop250_oscarwinner_oscarnomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarnomination',
            name='studio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oscarwinner',
            name='studio',
            field=models.CharField(max_length=500),
        ),
    ]
