# Generated by Django 4.2.3 on 2023-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0003_remove_movielist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
