# Generated by Django 4.2.3 on 2023-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0004_alter_oscarnomination_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscarnomination',
            name='studio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oscarwinner',
            name='studio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oscarwinner',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
