# Generated by Django 4.2.3 on 2023-08-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0005_personlist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personlist',
            name='description',
        ),
    ]
