# Generated by Django 4.2.3 on 2023-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0006_remove_personlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
