# Generated by Django 4.2.3 on 2023-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0007_alter_movielist_description_alter_movielist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlist',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
